apiVersion: apps/v1
kind: Deployment
metadata:
     name: beans-dev
     labels:
        app: beans
spec:
   selector:
       matchLabels:
            app: beans
   replicas: 2
   template:
       metadata:
           name: beans-dev
           labels:
              app: beans
       spec:
          containers:
          - name: beans-dev
            image: ipsegs/food-site:beans
            ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
     name: beans-service
spec:
   type: NodePort
   ports:
   - port: 80
   selector:
        app: beans


        
