apiVersion: apps/v1
kind: Deployment
metadata:
     name: rice-dev
     labels:
        app: rice
spec:
    selector:
        matchLabels:
              app: rice
    replicas: 2
    template:
         metadata:
              name: food-dev
              labels:
                  app: rice
         spec:
            containers:
            - name: rice-page
              image: ipsegs/food-site:rice
              ports:
              - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
     name: rice-service
     labels:
        app: rice
spec:
   type: NodePort
   ports:
   - port: 80
   selector:
        app: rice


